setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

library(shiny)
library(ggplot2)
library(bslib)

ui <- page_navbar(
  title = "Gunnison Sage-Grouse Conservation Engine",
  theme = bs_theme(
    version = 5,
    primary = "#14532d",
    secondary = "#475569",
    success = "#16a34a",
    danger = "#dc2626",
    base_font = font_google("Lato"),
    heading_font = font_google("Poppins"),
    "border-radius" = "0.375rem",
    "body-bg" = "#f8fafc"
  ),
  
  nav_panel(
    title = "Simulation Dashboard",
    layout_sidebar(
      sidebar = sidebar(
        title = "Model Parameters",
        width = 320,
        bg = "#ffffff",
        sliderInput("K", "Carrying Capacity (K)", min = 200, max = 1000, value = 500, step = 50),
        hr(),
        sliderInput("noise", "Environmental Stochasticity (Noise)", min = 0, max = 0.25, value = 0.08, step = 0.01),
        hr(),
        sliderInput("sims", "Simulated Future Realities", min = 10, max = 100, value = 30, step = 10)
      ),
      
      layout_columns(
        col_widths = c(6, 6),
        row_heights = "120px",
        
        value_box(
          title = "Target Carrying Capacity",
          value = textOutput("vb_k"),
          showcase = bsicons::bs_icon("tree"),
          theme = value_box_theme(bg = "#ffffff", fg = "#14532d")
        ),
        value_box(
          title = "Simulated Extinction Risk",
          value = textOutput("vb_risk"),
          showcase = bsicons::bs_icon("exclamation-triangle"),
          theme = value_box_theme(bg = "#ffffff", fg = "#dc2626")
        )
      ),
      
      card(
        full_screen = TRUE,
        wrapper = card_body(style = "padding: 24px; background: #ffffff;"),
        card_header(class = "border-0 bg-transparent pt-4 px-4 font-weight-bold", h5("Population Viability Analysis (PVA) Trajectories", style = "margin:0; font-family:'Poppins'; font-weight:600;")),
        plotOutput("popPlot", height = "420px"),
        card_footer(class = "border-0 bg-transparent pb-4 px-4 text-muted style-sm", "The shaded green bounds capture alternate population futures generated by random year-to-year weather fluctuations. The red baseline indicates resource limitation limits.")
      )
    )
  ),
  
  nav_panel(
    title = "Ecological Metadata",
    layout_columns(
      col_widths = c(12),
      card(
        wrapper = card_body(style = "padding: 32px; background: #ffffff;"),
        card_header(class = "border-0 bg-transparent font-weight-bold", h4("Project Metadata & Analytical Framework", style = "margin:0; font-family:'Poppins'; font-weight:600; color:#1e293b;")),
        markdown("
          This application implements a **stochastic, stage-structured Lefkovitch matrix model** combined with a linear density-dependent penalty function.
          
          The model structures the avian population into three distinct cohorts:
          1. **Chicks** (Age 0)
          2. **Subadults** (Age 1, first-year breeders)
          3. **Adults** (Age 2+, experienced breeders)
          
          ### Density Dependence & Stochastic Flight
          Every simulated year ($t$), the actual breeding fecundity undergoes a linear downward correction factor scaled to the resource ceiling constraint ($K$):
          
          $$\\text{Density Factor} = 1 - \\frac{N_{\\text{total}}}{K}$$
          
          Vital survival rates are pulled randomly from uniform distributions bounded by user-defined environmental noise variables, mimicking erratic climate cycles in the Rocky Mountain ranges.
        ")
      )
    )
  )
)

server <- function(input, output) {
  
  sim_data <- reactive({
    years <- 30
    initial_pop <- c(150, 80, 50)
    all_sims_list <- list()
    extinct_count <- 0
    
    for (sim in 1:input$sims) {
      pop_history <- matrix(0, nrow = 3, ncol = years + 1)
      pop_history[, 1] <- initial_pop
      is_extinct <- FALSE
      
      for (t in 1:years) {
        current_tot <- sum(pop_history[, t])
        
        if (current_tot <= 5) {
          is_extinct <- TRUE
        }
        
        density_factor <- max(0, 1 - (current_tot / input$K))
        f_subadult_actual <- 0.4 * density_factor
        f_adult_actual    <- 1.1 * density_factor
        
        noise_val <- runif(1, -input$noise, input$noise)
        p_chick   <- max(0, min(1, 0.30 + noise_val))
        p_subadult <- max(0, min(1, 0.45 + noise_val))
        p_adult    <- max(0, min(1, 0.65 + noise_val))
        
        A <- matrix(c(
          0,         f_subadult_actual, f_adult_actual,
          p_chick,   0,                 0,
          0,         p_subadult,        p_adult
        ), nrow = 3, byrow = TRUE)
        
        pop_history[, t + 1] <- A %*% pop_history[, t]
      }
      
      if (is_extinct) {
        extinct_count <- extinct_count + 1
      }
      
      total_pop <- colSums(pop_history)
      sim_df <- data.frame(
        Year = 0:years,
        Total = total_pop,
        Simulation = as.character(sim)
      )
      all_sims_list[[sim]] <- sim_df
    }
    
    list(
      plot_df = do.call(rbind, all_sims_list),
      risk_pct = round((extinct_count / input$sims) * 100, 1)
    )
  })
  
  output$vb_k <- renderText({ paste(input$K, "Individuals") })
  
  output$vb_risk <- renderText({ paste0(sim_data()$risk_pct, "%") })
  
  output$popPlot <- renderPlot({
    ggplot(sim_data()$plot_df, aes(x = Year, y = Total, group = Simulation)) +
      geom_line(color = "#14532d", alpha = 0.25, size = 1.0) +
      geom_hline(yintercept = input$K, linetype = "dashed", color = "#dc2626", size = 1.1) +
      theme_minimal(base_size = 14) +
      theme(
        text = element_text(family = "Lato", color = "#475569"),
        axis.text = element_text(color = "#64748b"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "#f1f5f9"),
        plot.margin = margin(20, 20, 20, 20)
      ) +
      labs(x = "Years into Future", y = "Total Estimated Population Size")
  })
}

shinyApp(ui = ui, server = server)